### ISSUE TITLE
proxying https does not work with python < 2.7.9

### ISSUE THREAD

**Issue by pabra** [efenka/hoxy#1]
In Python versions prior 2.7.9, the `ssl` module had no attribute `_create_unverified_context`.

The hoxy raises:

```
AttributeError: 'module' object has no attribute '_create_unverified_context'
```

A possible solution was posted here:
https://dnaeon.github.io/disable-python-ssl-verification/
